[package]
name = "visit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parse = { path = "../parse"}

[lib]
name = "visit"
path = "src/lib.rs"



[[bin]]
name = "parse_main"
path = "src/main.rs"