[package]
name = "tokenize"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.4"

[lib]
name = "tokenize"
path = "src/lib.rs"
